Work Section
mhassa204/My-Portfolio pull request #2
Opened 2023-07-12 11:53 UTC by mhassa204

"Works" section added
"about-myself" section added
In order to lay out the elements in "Works" section CSS Grid and Flexbox combine used.

2023-07-12 12:18 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @mhassa204 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- UI is looking great ✔
- Proper use of HTML semantics ✔
- Correct use of GitHub Flow ✔
- Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-12 12:18 UTC, AbelG101 commented on style.css
> +}
- [ ] It appears that the `:hover` and `:active` (pressed) button stylings have not been implemented, as shown in the Figma design below. As a front-end developer, it's important to pay close attention to details like this, as they contribute to a polished UI. Please ensure that these stylings are added to the buttons. Thank you.
- Here's the Figma design as a reference:
  ![firefox_7KIb3eS8J1](https://github.com/mhassa204/My-Portfolio/assets/104968236/dd1809b5-836e-40f6-ae5f-fa91549c7e41)
- [ ] This applies to the "Get my resume" button in the "About section" as well.

2023-07-12 12:18 UTC, AbelG101 commented on index.html
> +       </div>
- [ ] Ouch! this is close but to ensure proper HTML semantics, I recommend using an unordered list `ul` to group the technology categories ('Languages', 'Frameworks', and 'Skills'), with each category represented by a list item `li`, instead of using a `div` element to wrap them all. This approach would make the markup more structured and semantically meaningful. Thank you for considering this suggestion.

2023-07-12 12:18 UTC, AbelG101 commented on index.html
> +        <h1>About Myself</h1>
- [ ] o adhere to HTML semantics and improve the SEO of the page, it's recommended to have only one h1 tag per webpage, which should describe the main topic of the page. I noticed that you're using an h1 tag for the 'About myself' section, but since it's not the main heading of the page, I suggest using a lower-level heading tag like h2, h3, etc. instead. This would improve the structure and semantics of the page, and also help search engines understand the hierarchy and relevance of the content. Thank you for considering this recommendation. 😊

2023-07-12 14:46 UTC, franclobo requested changes
Hi @mhassa204, 

# Required Changes ♻️

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Github flow ✔️ 



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-13 15:29 UTC, mhassa204 commented on index.html
> +        </div>
Fixed

2023-07-13 15:39 UTC, merged