Add desktop version
mhassa204/My-Portfolio pull request #4
Opened 2023-07-19 20:54 UTC by mhassa204

Added html and css for responsive desktop version.

2023-07-19 22:39 UTC, ademibowale requested changes
## STATUS: Changes Required :recycle:

### Hi @mhassa204  , 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight 🥇

✅ Descriptive Pull Request title and summary. ✔️
✅ Good use of Github flow ✔️
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.

### Changes Required

- [x]  _Please check the comments under the review._
- [ ] I would kindly suggest you make your pull request summary to be more descriptive, PR descriptions can be good indicators for managers and peers to re-visit a problem that may have been communicated ineffectively or not needed! Writing a good summary for your reviewers opens the door for reviewers who haven't been working in the same trench as you
- [ ] 
![professional PR hello mv](https://github.com/mhassa204/My-Portfolio/assets/92458236/a5cb5779-53e9-481b-bff3-35b7da997d41)


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @Adebowale ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-19 22:39 UTC, ademibowale commented on style.css
> +    grid-template-columns: repeat(2, 1fr);
- [ ] You have done a great job on this milestone, I do really appreciate your effort  kudos to you, but there are a few issues you still need to address to make this project look professional like the Figma template design you are chosen
- [ ] I would kindly suggest you to work more on this  Desktop version should be fully responsive.what if you can use and according to the project requirement Minimum mobile screen size should be 375px.,please kindly fix this to make your website  responsive for proper user interface

https://github.com/mhassa204/My-Portfolio/assets/92458236/c79a3027-646d-4384-b22d-ba5d293abd77

2023-07-19 22:39 UTC, ademibowale commented on style.css
> +  }
- [ ] Your website is great but still needs to work on the responsiveness, as you can see I attached the screenshot of your UI below  Minimum mobile screen size should be `375`px. kindly fix the white space to make it look professional and user friendly 

![Screenshot 2023-07-19 225613](https://github.com/mhassa204/My-Portfolio/assets/92458236/04811f9f-0a22-4c18-beb5-9d2e458860c8)

2023-07-21 12:21 UTC, rica213 requested changes
# 🟡 STATUS: REQUIRED CHANGES ♻️ 
Hi Ali 
My name is Larissa. Your code reviewer 🥰

Thank you for implementing the required changes from the previous reviewer. However, by doing so you unintentionally introduce some inconsistencies in your design that I mentioned below 👇🏽 
Kindly fix them. Thank you!

<img src="https://media0.giphy.com/media/6riEABBXLBsfplIFMw/giphy.gif"/>

Happy coding!
## Highlights
Good Design ✔️
Professional Documentation ✔️
No Linter errors ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend considering them as they can improve your code._


# Cheers, and Happy coding 🖥️

## If anything is not 100% clear, kindly mention me in your comment and I will reply ASAP 🤞

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 12:21 UTC, rica213 commented on style.css
> +  }
- [ ] Kindly make sure that your design is layered properly and follows the Figma template. It will improve your design 🌹 

Your design 👇🏽 

![Screenshot from 2023-07-21 15-10-14](https://github.com/mhassa204/My-Portfolio/assets/10439283/ec5e0552-b0e8-4f20-8cca-343a5035d379)

2023-07-21 12:21 UTC, rica213 commented on style.css
> +  }
- [ ]  Kindly make sure that your design is layered properly and follows the Figma template. It will improve your design 🙏🏽 

Your design 👇🏽 

![Screenshot from 2023-07-21 15-10-23](https://github.com/mhassa204/My-Portfolio/assets/10439283/5b8b0710-840e-4890-b9e2-01a18ddf0361)

2023-07-21 12:21 UTC, rica213 commented on index.html
>        </div>
- [ ] In your about section, the contents are overlapping, kindly fix that. It is crucial to be consistent with the design given ❤️ 
your design 👇🏽 

![Screenshot from 2023-07-21 15-14-09](https://github.com/mhassa204/My-Portfolio/assets/10439283/93730156-8c7e-4aa7-9fe2-0c4b2a427706)

2023-07-21 14:44 UTC, rica213 approved these changes
# 🟢 STATUS: APPROVED
Hi Ali 

Your project is complete!  You implemented all the required changes and fixed your design 🛸 🛸 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/l41YmQjOz9qg2Ecow/giphy.gif"/>

## Highlights

- [ ] No Linters errors ✔️ 
- [ ] Correct Github flow ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend considering them as they can improve your code. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-21 15:00 UTC, merged